-- =====================================================
-- COMPLETE MERGE STATEMENTS FOR DIMENSIONAL AND FACT TABLES
-- Database: SEATTLE_DW
-- =====================================================

USE DATABASE SEATTLE_DW;

USE SCHEMA DW;

-- =====================================================
-- 1. DATE DIMENSION (Run First - Independent)
-- =====================================================
MERGE INTO DIM_DATE AS TARGET
USING (
    WITH DATE_RANGE AS (
        SELECT DATEADD(DAY, SEQ4(), '2020-01-01'::DATE) AS FULL_DATE
        FROM TABLE(GENERATOR(ROWCOUNT => 2557))  -- 7 years
    )
    SELECT 
        TO_NUMBER(TO_CHAR(FULL_DATE, 'YYYYMMDD')) AS DATE_KEY,
        FULL_DATE,
        YEAR(FULL_DATE) AS YEAR,
        QUARTER(FULL_DATE) AS QUARTER,
        MONTH(FULL_DATE) AS MONTH,
        MONTHNAME(FULL_DATE) AS MONTH_NAME,
        DAY(FULL_DATE) AS DAY_OF_MONTH,
        DAYOFWEEK(FULL_DATE) AS DAY_OF_WEEK,
        DAYNAME(FULL_DATE) AS DAY_NAME,
        WEEKOFYEAR(FULL_DATE) AS WEEK_OF_YEAR,
        CASE WHEN DAYOFWEEK(FULL_DATE) IN (0, 6) THEN TRUE ELSE FALSE END AS IS_WEEKEND,
        CASE 
            WHEN MONTH(FULL_DATE) >= 10 THEN YEAR(FULL_DATE) + 1
            ELSE YEAR(FULL_DATE)
        END AS FISCAL_YEAR,
        CASE 
            WHEN MONTH(FULL_DATE) IN (10, 11, 12) THEN 1
            WHEN MONTH(FULL_DATE) IN (1, 2, 3) THEN 2
            WHEN MONTH(FULL_DATE) IN (4, 5, 6) THEN 3
            ELSE 4
        END AS FISCAL_QUARTER
    FROM DATE_RANGE
    WHERE FULL_DATE <= '2026-12-31'
) AS SOURCE
ON TARGET.DATE_KEY = SOURCE.DATE_KEY
WHEN NOT MATCHED THEN
    INSERT (DATE_KEY, FULL_DATE, YEAR, QUARTER, MONTH, MONTH_NAME, 
            DAY_OF_MONTH, DAY_OF_WEEK, DAY_NAME, WEEK_OF_YEAR, 
            IS_WEEKEND, FISCAL_YEAR, FISCAL_QUARTER)
    VALUES (SOURCE.DATE_KEY, SOURCE.FULL_DATE, SOURCE.YEAR, SOURCE.QUARTER, 
            SOURCE.MONTH, SOURCE.MONTH_NAME, SOURCE.DAY_OF_MONTH, 
            SOURCE.DAY_OF_WEEK, SOURCE.DAY_NAME, SOURCE.WEEK_OF_YEAR, 
            SOURCE.IS_WEEKEND, SOURCE.FISCAL_YEAR, SOURCE.FISCAL_QUARTER);

-- =====================================================
-- 2. LOCATION DIMENSION (Run Second)
-- =====================================================
-- Add unknown location for NULL handling
MERGE INTO DIM_LOCATION AS TARGET
USING (SELECT '-1' AS ZIP_CODE, 'UNKNOWN' AS CITY, 'UNKNOWN' AS COUNTY, 
              'UNKNOWN' AS STATE, 'UN' AS STATE_ABBR, -1 AS STATE_FIPS) AS SOURCE
ON TARGET.ZIP_CODE = SOURCE.ZIP_CODE
WHEN NOT MATCHED THEN
    INSERT (ZIP_CODE, CITY, COUNTY, STATE, STATE_ABBR, STATE_FIPS)
    VALUES (SOURCE.ZIP_CODE, SOURCE.CITY, SOURCE.COUNTY, 
            SOURCE.STATE, SOURCE.STATE_ABBR, SOURCE.STATE_FIPS);

-- Load from location staging table
-- =====================================================
-- FIXED LOCATION DIMENSION MERGE - HANDLES DUPLICATES
-- =====================================================
USE DATABASE SEATTLE_DW;
USE SCHEMA DW;

-- First, check for duplicates in your staging table
SELECT ZIP_CODE, COUNT(*) as DUP_COUNT
FROM (
    SELECT DISTINCT
        CAST(ZIPCODE AS VARCHAR(20)) AS ZIP_CODE,
        CITY,
        COUNTY,
        STATE,
        STATE_ABBR,
        STATE_FIPS
    FROM SEATTLE_DW.STAGE.STG_LOCATION
    WHERE ZIPCODE IS NOT NULL AND ZIPCODE != ''
)
GROUP BY ZIP_CODE
HAVING COUNT(*) > 1;

-- Add unknown location for NULL handling
MERGE INTO DIM_LOCATION AS TARGET
USING (SELECT '-1' AS ZIP_CODE, 'UNKNOWN' AS CITY, 'UNKNOWN' AS COUNTY, 
              'UNKNOWN' AS STATE, 'UN' AS STATE_ABBR, -1 AS STATE_FIPS) AS SOURCE
ON TARGET.ZIP_CODE = SOURCE.ZIP_CODE
WHEN NOT MATCHED THEN
    INSERT (ZIP_CODE, CITY, COUNTY, STATE, STATE_ABBR, STATE_FIPS)
    VALUES (SOURCE.ZIP_CODE, SOURCE.CITY, SOURCE.COUNTY, 
            SOURCE.STATE, SOURCE.STATE_ABBR, SOURCE.STATE_FIPS);

-- FIXED: Load from location staging table - handling duplicates by taking first occurrence
MERGE INTO DIM_LOCATION AS TARGET
USING (
    SELECT 
        ZIP_CODE,
        FIRST_VALUE(CITY) OVER (PARTITION BY ZIP_CODE ORDER BY CITY) AS CITY,
        FIRST_VALUE(COUNTY) OVER (PARTITION BY ZIP_CODE ORDER BY COUNTY) AS COUNTY,
        FIRST_VALUE(STATE) OVER (PARTITION BY ZIP_CODE ORDER BY STATE) AS STATE,
        FIRST_VALUE(STATE_ABBR) OVER (PARTITION BY ZIP_CODE ORDER BY STATE_ABBR) AS STATE_ABBR,
        FIRST_VALUE(STATE_FIPS) OVER (PARTITION BY ZIP_CODE ORDER BY STATE_FIPS) AS STATE_FIPS
    FROM (
        SELECT DISTINCT
            CAST(ZIPCODE AS VARCHAR(20)) AS ZIP_CODE,
            CITY,
            COUNTY,
            STATE,
            STATE_ABBR,
            STATE_FIPS
        FROM SEATTLE_DW.STAGE.STG_LOCATION
        WHERE ZIPCODE IS NOT NULL AND ZIPCODE != ''
    )
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ZIP_CODE ORDER BY ZIP_CODE) = 1
) AS SOURCE
ON TARGET.ZIP_CODE = SOURCE.ZIP_CODE
WHEN NOT MATCHED THEN
    INSERT (ZIP_CODE, CITY, COUNTY, STATE, STATE_ABBR, STATE_FIPS)
    VALUES (SOURCE.ZIP_CODE, SOURCE.CITY, SOURCE.COUNTY, 
            SOURCE.STATE, SOURCE.STATE_ABBR, SOURCE.STATE_FIPS)
WHEN MATCHED AND (
    COALESCE(TARGET.CITY, '') != COALESCE(SOURCE.CITY, '') OR
    COALESCE(TARGET.COUNTY, '') != COALESCE(SOURCE.COUNTY, '') OR
    COALESCE(TARGET.STATE, '') != COALESCE(SOURCE.STATE, '')
) THEN
    UPDATE SET 
        CITY = SOURCE.CITY,
        COUNTY = SOURCE.COUNTY,
        STATE = SOURCE.STATE,
        STATE_ABBR = SOURCE.STATE_ABBR,
        STATE_FIPS = SOURCE.STATE_FIPS,
        UPDATED_TIMESTAMP = CURRENT_TIMESTAMP();

-- Add ZIP codes from pet data not in location table
MERGE INTO DIM_LOCATION AS TARGET
USING (
    SELECT ZIP_CODE
    FROM (
        SELECT DISTINCT 
            TRIM(ZIP_CODE) AS ZIP_CODE
        FROM SEATTLE_DW.STAGE.STG_PET_LICENSE
        WHERE ZIP_CODE IS NOT NULL 
          AND TRIM(ZIP_CODE) != ''
          AND LENGTH(TRIM(ZIP_CODE)) <= 10  -- Reasonable ZIP code length
          AND NOT EXISTS (
              SELECT 1 FROM DIM_LOCATION 
              WHERE ZIP_CODE = TRIM(STG_PET_LICENSE.ZIP_CODE)
          )
    )
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ZIP_CODE ORDER BY ZIP_CODE) = 1
) AS SOURCE
ON TARGET.ZIP_CODE = SOURCE.ZIP_CODE
WHEN NOT MATCHED THEN
    INSERT (ZIP_CODE, CITY, COUNTY, STATE, STATE_ABBR, STATE_FIPS)
    VALUES (SOURCE.ZIP_CODE, 'Seattle', 'King', 'Washington', 'WA', 53);

-- Verify the results
SELECT COUNT(*) AS LOCATION_COUNT, COUNT(DISTINCT ZIP_CODE) AS UNIQUE_ZIPS 
FROM DIM_LOCATION;
-- =====================================================
-- 3. BREED DIMENSION (Run Third)
-- =====================================================
-- Add unknown breed for NULL handling
MERGE INTO DIM_BREED AS TARGET
USING (SELECT 'UNKNOWN' AS SPECIES, 'UNKNOWN' AS PRIMARY_BREED, 
              'NONE' AS SECONDARY_BREED, 'UNKNOWN - NONE' AS BREED_COMBINATION, 
              FALSE AS IS_MIXED_BREED) AS SOURCE
ON TARGET.SPECIES = SOURCE.SPECIES 
   AND TARGET.PRIMARY_BREED = SOURCE.PRIMARY_BREED
   AND COALESCE(TARGET.SECONDARY_BREED, 'NONE') = SOURCE.SECONDARY_BREED
WHEN NOT MATCHED THEN
    INSERT (SPECIES, PRIMARY_BREED, SECONDARY_BREED, BREED_COMBINATION, IS_MIXED_BREED)
    VALUES (SOURCE.SPECIES, SOURCE.PRIMARY_BREED, SOURCE.SECONDARY_BREED,
            SOURCE.BREED_COMBINATION, SOURCE.IS_MIXED_BREED);

-- Load from pet staging table
MERGE INTO DIM_BREED AS TARGET
USING (
    SELECT DISTINCT
        UPPER(TRIM(COALESCE(SPECIES, 'UNKNOWN'))) AS SPECIES,
        UPPER(TRIM(COALESCE(PRIMARY_BREED, 'UNKNOWN'))) AS PRIMARY_BREED,
        UPPER(TRIM(COALESCE(NULLIF(SECONDARY_BREED, ''), 'NONE'))) AS SECONDARY_BREED,
        UPPER(TRIM(COALESCE(PRIMARY_BREED, 'UNKNOWN'))) || ' - ' || 
            UPPER(TRIM(COALESCE(NULLIF(SECONDARY_BREED, ''), 'NONE'))) AS BREED_COMBINATION,
        CASE 
            WHEN SECONDARY_BREED IS NOT NULL 
                 AND TRIM(SECONDARY_BREED) != '' 
                 AND UPPER(TRIM(SECONDARY_BREED)) NOT IN ('NONE', 'NULL')
            THEN TRUE 
            ELSE FALSE 
        END AS IS_MIXED_BREED
    FROM SEATTLE_DW.STAGE.STG_PET_LICENSE
) AS SOURCE
ON TARGET.SPECIES = SOURCE.SPECIES 
   AND TARGET.PRIMARY_BREED = SOURCE.PRIMARY_BREED
   AND COALESCE(TARGET.SECONDARY_BREED, 'NONE') = COALESCE(SOURCE.SECONDARY_BREED, 'NONE')
WHEN NOT MATCHED THEN
    INSERT (SPECIES, PRIMARY_BREED, SECONDARY_BREED, BREED_COMBINATION, IS_MIXED_BREED)
    VALUES (SOURCE.SPECIES, SOURCE.PRIMARY_BREED, SOURCE.SECONDARY_BREED,
            SOURCE.BREED_COMBINATION, SOURCE.IS_MIXED_BREED)
WHEN MATCHED AND (
    TARGET.BREED_COMBINATION != SOURCE.BREED_COMBINATION OR
    TARGET.IS_MIXED_BREED != SOURCE.IS_MIXED_BREED
) THEN
    UPDATE SET 
        BREED_COMBINATION = SOURCE.BREED_COMBINATION,
        IS_MIXED_BREED = SOURCE.IS_MIXED_BREED,
        UPDATED_TIMESTAMP = CURRENT_TIMESTAMP();

-- =====================================================
-- 4. PET DIMENSION (Run Fourth)
-- =====================================================
-- Add unknown pet for NULL handling
MERGE INTO DIM_PET AS TARGET
USING (SELECT '-1' AS LICENSE_NUMBER, 'UNKNOWN' AS PET_NAME) AS SOURCE
ON TARGET.LICENSE_NUMBER = SOURCE.LICENSE_NUMBER
WHEN NOT MATCHED THEN
    INSERT (LICENSE_NUMBER, PET_NAME)
    VALUES (SOURCE.LICENSE_NUMBER, SOURCE.PET_NAME);

-- Load from pet staging table
MERGE INTO DIM_PET AS TARGET
USING (
    SELECT DISTINCT
        TRIM(LICENSE_NUMBER) AS LICENSE_NUMBER,
        TRIM(COALESCE(ANIMALS_NAME, 'NO NAME')) AS PET_NAME
    FROM SEATTLE_DW.STAGE.STG_PET_LICENSE
    WHERE LICENSE_NUMBER IS NOT NULL 
      AND TRIM(LICENSE_NUMBER) != ''
      AND UPPER(LICENSE_NUMBER) NOT IN ('NULL', 'NA', 'N/A')
) AS SOURCE
ON TARGET.LICENSE_NUMBER = SOURCE.LICENSE_NUMBER
WHEN NOT MATCHED THEN
    INSERT (LICENSE_NUMBER, PET_NAME)
    VALUES (SOURCE.LICENSE_NUMBER, SOURCE.PET_NAME)
WHEN MATCHED AND TARGET.PET_NAME != SOURCE.PET_NAME THEN
    UPDATE SET 
        PET_NAME = SOURCE.PET_NAME,
        UPDATED_TIMESTAMP = CURRENT_TIMESTAMP();

-- =====================================================
-- 5. FACT TABLE (Run Last - After All Dimensions)
-- =====================================================

-- =====================================================
-- WORKING FACT TABLE LOAD SCRIPT
-- =====================================================
USE DATABASE SEATTLE_DW;
USE SCHEMA DW;

-- 1. Check staging data
SELECT COUNT(*) AS STAGING_COUNT FROM SEATTLE_DW.STAGE.STG_PET_LICENSE;

-- 2. Check date formats (first 10 unique dates)
SELECT 
    LICENSE_ISSUE_DATE,
    TRY_TO_DATE(LICENSE_ISSUE_DATE, 'MM/DD/YYYY') AS PARSED_DATE,
    COUNT(*) AS COUNT
FROM SEATTLE_DW.STAGE.STG_PET_LICENSE
GROUP BY LICENSE_ISSUE_DATE
LIMIT 10;

-- 3. Clear fact table
TRUNCATE TABLE FACT_PETLICENSE;

-- 4. WORKING FACT TABLE INSERT
INSERT INTO FACT_PETLICENSE (
    DATE_KEY,
    LOCATION_KEY,
    BREED_KEY,
    PET_KEY,
    LICENSE_NUMBER,
    LICENSE_COUNT
)
SELECT 
    -- Parse date with multiple format attempts
    COALESCE(
        TO_NUMBER(TO_CHAR(TRY_TO_DATE(s.LICENSE_ISSUE_DATE, 'MM/DD/YYYY'), 'YYYYMMDD')),
        TO_NUMBER(TO_CHAR(TRY_TO_DATE(s.LICENSE_ISSUE_DATE, 'M/D/YYYY'), 'YYYYMMDD')),
        TO_NUMBER(TO_CHAR(TRY_TO_DATE(s.LICENSE_ISSUE_DATE, 'YYYY-MM-DD'), 'YYYYMMDD')),
        20200101  -- Default date
    ) AS DATE_KEY,
    
    -- Get Location Key using JOIN instead of subquery
    COALESCE(l.LOCATION_KEY, def_loc.LOCATION_KEY) AS LOCATION_KEY,
    
    -- Get Breed Key using JOIN
    COALESCE(b.BREED_KEY, def_breed.BREED_KEY) AS BREED_KEY,
    
    -- Get Pet Key using JOIN
    COALESCE(p.PET_KEY, def_pet.PET_KEY) AS PET_KEY,
    
    s.LICENSE_NUMBER,
    1 AS LICENSE_COUNT
    
FROM SEATTLE_DW.STAGE.STG_PET_LICENSE s

-- Left join for location
LEFT JOIN DIM_LOCATION l 
    ON TRIM(l.ZIP_CODE) = TRIM(s.ZIP_CODE)

-- Left join for breed (simplified matching)
LEFT JOIN DIM_BREED b 
    ON UPPER(TRIM(COALESCE(b.SPECIES, 'UNKNOWN'))) = UPPER(TRIM(COALESCE(s.SPECIES, 'UNKNOWN')))
    AND UPPER(TRIM(COALESCE(b.PRIMARY_BREED, 'UNKNOWN'))) = UPPER(TRIM(COALESCE(s.PRIMARY_BREED, 'UNKNOWN')))

-- Left join for pet
LEFT JOIN DIM_PET p 
    ON TRIM(p.LICENSE_NUMBER) = TRIM(s.LICENSE_NUMBER)

-- Cross join to get default values
CROSS JOIN (SELECT LOCATION_KEY FROM DIM_LOCATION WHERE ZIP_CODE = '-1' LIMIT 1) def_loc
CROSS JOIN (SELECT MIN(BREED_KEY) AS BREED_KEY FROM DIM_BREED WHERE SPECIES = 'UNKNOWN') def_breed
CROSS JOIN (SELECT PET_KEY FROM DIM_PET WHERE LICENSE_NUMBER = '-1' LIMIT 1) def_pet

WHERE s.LICENSE_NUMBER IS NOT NULL
  AND TRIM(s.LICENSE_NUMBER) != ''
  AND s.LICENSE_ISSUE_DATE IS NOT NULL;

-- 5. Check results
SELECT COUNT(*) AS FACT_COUNT FROM FACT_PETLICENSE;

-- 6. Fixed debug queries (no EXISTS in aggregate)
SELECT 'Debug: Staging records' AS CHECK_TYPE, COUNT(*) AS COUNT
FROM SEATTLE_DW.STAGE.STG_PET_LICENSE
WHERE LICENSE_NUMBER IS NOT NULL;

SELECT 'Debug: Valid dates' AS CHECK_TYPE, COUNT(*) AS COUNT
FROM SEATTLE_DW.STAGE.STG_PET_LICENSE
WHERE TRY_TO_DATE(LICENSE_ISSUE_DATE, 'MM/DD/YYYY') IS NOT NULL;

-- 7. Check dimension matches using JOINs
SELECT 
    'Dimension Matches' AS CHECK_TYPE,
    COUNT(DISTINCT s.LICENSE_NUMBER) AS TOTAL_STAGING,
    COUNT(DISTINCT l.LOCATION_KEY) AS MATCHED_LOCATIONS,
    COUNT(DISTINCT p.PET_KEY) AS MATCHED_PETS,
    COUNT(DISTINCT b.BREED_KEY) AS MATCHED_BREEDS
FROM SEATTLE_DW.STAGE.STG_PET_LICENSE s
LEFT JOIN DIM_LOCATION l ON TRIM(l.ZIP_CODE) = TRIM(s.ZIP_CODE)
LEFT JOIN DIM_PET p ON TRIM(p.LICENSE_NUMBER) = TRIM(s.LICENSE_NUMBER)
LEFT JOIN DIM_BREED b 
    ON UPPER(TRIM(b.SPECIES)) = UPPER(TRIM(s.SPECIES))
    AND UPPER(TRIM(b.PRIMARY_BREED)) = UPPER(TRIM(s.PRIMARY_BREED));

-- 8. If still no data, check if default records exist
SELECT 'Default Records Check' AS CHECK_TYPE;
SELECT 'Location -1' AS RECORD, COUNT(*) AS EXISTS_FLAG FROM DIM_LOCATION WHERE ZIP_CODE = '-1'
UNION ALL
SELECT 'Breed UNKNOWN', COUNT(*) FROM DIM_BREED WHERE SPECIES = 'UNKNOWN'
UNION ALL
SELECT 'Pet -1', COUNT(*) FROM DIM_PET WHERE LICENSE_NUMBER = '-1';