
USE DATABASE SEATTLE_DW;
USE SCHEMA DW;

-- 1. DATE DIMENSION
CREATE OR REPLACE TABLE DIM_DATE (
    DATE_KEY INT PRIMARY KEY,           -- Format: YYYYMMDD
    FULL_DATE DATE NOT NULL,
    YEAR INT,
    QUARTER INT,
    MONTH INT,
    MONTH_NAME VARCHAR(20),
    DAY_OF_MONTH INT,
    DAY_OF_WEEK INT,
    DAY_NAME VARCHAR(20),
    WEEK_OF_YEAR INT,
    IS_WEEKEND BOOLEAN,
    FISCAL_YEAR INT,
    FISCAL_QUARTER INT,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 2. LOCATION DIMENSION
CREATE OR REPLACE TABLE DIM_LOCATION (
    LOCATION_KEY INT IDENTITY(1,1) PRIMARY KEY,
    ZIP_CODE VARCHAR(20),
    CITY VARCHAR(100),
    COUNTY VARCHAR(100),
    STATE VARCHAR(100),
    STATE_ABBR VARCHAR(10),
    STATE_FIPS INT,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 3. BREED DIMENSION
CREATE OR REPLACE TABLE DIM_BREED (
    BREED_KEY INT IDENTITY(1,1) PRIMARY KEY,
    SPECIES VARCHAR(100),
    PRIMARY_BREED VARCHAR(200),
    SECONDARY_BREED VARCHAR(200),
    BREED_COMBINATION VARCHAR(400),  -- Concatenation of primary and secondary
    IS_MIXED_BREED BOOLEAN,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- 4. PET DIMENSION (Optional - for storing individual pet information)
CREATE OR REPLACE TABLE DIM_PET (
    PET_KEY INT IDENTITY(1,1) PRIMARY KEY,
    LICENSE_NUMBER VARCHAR(100) UNIQUE,
    PET_NAME VARCHAR(500),
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE TABLE FACT_PETLICENSE (
    LICENSE_FACT_KEY INT IDENTITY(1,1) PRIMARY KEY,
    DATE_KEY INT NOT NULL,
    LOCATION_KEY INT NOT NULL,
    BREED_KEY INT NOT NULL,
    PET_KEY INT NOT NULL,
    LICENSE_NUMBER VARCHAR(100),
    LICENSE_COUNT INT DEFAULT 1,  -- Always 1 for transaction-level grain
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    
    -- Foreign Key Constraints
    CONSTRAINT FK_DATE FOREIGN KEY (DATE_KEY) REFERENCES DIM_DATE(DATE_KEY),
    CONSTRAINT FK_LOCATION FOREIGN KEY (LOCATION_KEY) REFERENCES DIM_LOCATION(LOCATION_KEY),
    CONSTRAINT FK_BREED FOREIGN KEY (BREED_KEY) REFERENCES DIM_BREED(BREED_KEY),
    CONSTRAINT FK_PET FOREIGN KEY (PET_KEY) REFERENCES DIM_PET(PET_KEY)
);