use database SEATTLE_DW;
use schema STAGE;
-- Staging table for raw CSV data
CREATE OR REPLACE TABLE STG_PET_LICENSE (
    LICENSE_ISSUE_DATE VARCHAR(100),
    LICENSE_NUMBER VARCHAR(100),
    ANIMALS_NAME VARCHAR(500),
    SPECIES VARCHAR(100),
    PRIMARY_BREED VARCHAR(200),
    SECONDARY_BREED VARCHAR(200),
    ZIP_CODE VARCHAR(20)
);

-- Staging table for location data from Excel
CREATE OR REPLACE TABLE STG_LOCATION (
    STATE_FIPS INT,
    STATE VARCHAR(100),
    STATE_ABBR VARCHAR(10),
    ZIPCODE VARCHAR(20),
    COUNTY VARCHAR(100),
    CITY VARCHAR(100)
);